import type { Workspace } from "@/lib/workspace";

export const demoWorkspace = {
  currentMemberId: "diar",
  members: [
    { id: "diar", name: "Diar", role: "Board member", skills: ["Product", "Technology"] },
    { id: "aino", name: "Aino Laine", role: "Community lead", skills: ["Community", "Outreach"] },
    {
      id: "elias",
      name: "Elias Koski",
      role: "Project lead",
      skills: ["Operations", "Partnerships"],
    },
    { id: "noora", name: "Noora Niemi", role: "Communications", skills: ["Design", "Marketing"] },
    { id: "leo", name: "Leo Virtanen", role: "Volunteer", skills: ["Photography", "Technology"] },
  ],
  projects: [
    {
      id: "founder-night",
      title: "Founder Night",
      description:
        "An evening of honest founder stories, new connections, and ideas worth building.",
      status: "doing",
      assigneeIds: ["elias", "aino", "noora"],
      dueDate: "2026-10-22",
      location: "Platform6, Tampere",
    },
    {
      id: "campus-builders",
      title: "Campus Builders",
      description:
        "Bring students together to form teams and turn early ideas into working projects.",
      status: "todo",
      assigneeIds: ["diar", "leo"],
      dueDate: "2026-11-05",
      location: "Tampere University, City Centre Campus",
    },
  ],
  tasks: [
    {
      id: "confirm-speakers",
      title: "Confirm the founder speakers",
      description: "Invite two local founders and confirm the topics they want to share.",
      status: "doing",
      projectId: "founder-night",
      assigneeIds: ["elias"],
      dueDate: "2026-10-08",
    },
    {
      id: "book-venue",
      title: "Book the space at Platform6",
      description: "Confirm the room, capacity, and access for the organizing team.",
      status: "done",
      projectId: "founder-night",
      assigneeIds: ["elias"],
      dueDate: "2026-10-02",
    },
    {
      id: "founder-visuals",
      title: "Design the Founder Night visuals",
      description: "Prepare the project cover and social posts for the launch.",
      status: "doing",
      projectId: "founder-night",
      assigneeIds: ["noora"],
      dueDate: "2026-10-09",
    },
    {
      id: "welcome-team",
      title: "Find a welcome team",
      description: "Ask members in Telegram who would like to greet guests and help with check-in.",
      status: "todo",
      projectId: "founder-night",
      assigneeIds: ["aino"],
      dueDate: "2026-10-12",
    },
    {
      id: "photography",
      title: "Plan photos for Founder Night",
      description: "Agree on the moments to capture and where to share the album afterward.",
      status: "todo",
      projectId: "founder-night",
      assigneeIds: ["leo"],
      dueDate: "2026-10-16",
    },
    {
      id: "founder-run-sheet",
      title: "Write the evening run sheet",
      description: "Draft the timings for setup, talks, questions, and networking.",
      status: "todo",
      projectId: "founder-night",
      assigneeIds: ["elias", "aino"],
      dueDate: "2026-10-15",
    },
    {
      id: "campus-format",
      title: "Choose the Campus Builders format",
      description:
        "Keep the first session practical, with introductions, team formation, and time to build.",
      status: "doing",
      projectId: "campus-builders",
      assigneeIds: ["diar"],
      dueDate: "2026-10-13",
    },
    {
      id: "campus-room",
      title: "Reserve a campus room",
      description: "Find a room with tables, power, and space for small teams.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["leo"],
      dueDate: "2026-10-16",
    },
    {
      id: "campus-invite",
      title: "Draft the student invitation",
      description: "Explain what participants can build and that no finished idea is required.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["noora", "diar"],
      dueDate: "2026-10-20",
    },
    {
      id: "campus-mentors",
      title: "Invite mentors for builder teams",
      description: "Ask a few experienced members to help teams get past their first blockers.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["aino"],
      dueDate: "2026-10-23",
    },
    {
      id: "board-agenda",
      title: "Prepare the next board agenda",
      description: "Collect decisions and open questions from this week's project discussions.",
      status: "doing",
      projectId: null,
      assigneeIds: ["diar"],
      dueDate: "2026-10-06",
    },
    {
      id: "member-onboarding",
      title: "Refresh member onboarding",
      description: "Make it easy for new members to find a project and meet the team.",
      status: "todo",
      projectId: null,
      assigneeIds: ["aino", "noora"],
      dueDate: "2026-10-14",
    },
    {
      id: "drive-folder",
      title: "Organize the shared project documents",
      description: "Put the current briefs and checklists in one shared Drive folder.",
      status: "done",
      projectId: null,
      assigneeIds: ["leo"],
      dueDate: "2026-10-01",
    },
  ],
  channels: [
    { id: "general", name: "general", kind: "general" },
    { id: "board", name: "board", kind: "general" },
    { id: "ideas", name: "ideas", kind: "general" },
    {
      id: "founder-night-channel",
      name: "Founder Night",
      kind: "project",
      projectId: "founder-night",
    },
    {
      id: "campus-builders-channel",
      name: "Campus Builders",
      kind: "project",
      projectId: "campus-builders",
    },
  ],
  messages: [
    {
      id: "general-hello",
      conversation: { kind: "channel", id: "general" },
      authorId: "aino",
      text: "Welcome back! Founder Night and Campus Builders are taking shape. Pick a task if you'd like to help.",
      createdAt: "2026-10-03T08:15:00.000Z",
    },
    {
      id: "general-help",
      conversation: { kind: "channel", id: "general" },
      authorId: "leo",
      text: "I'm in for photos at Founder Night. I'll also check rooms for the campus session.",
      createdAt: "2026-10-03T08:28:00.000Z",
    },
    {
      id: "board-agenda-message",
      conversation: { kind: "channel", id: "board" },
      authorId: "diar",
      text: "Let's bring the project budgets and volunteer needs to Tuesday's board meeting.",
      createdAt: "2026-10-03T09:00:00.000Z",
    },
    {
      id: "idea-breakfast",
      conversation: { kind: "channel", id: "ideas" },
      authorId: "noora",
      text: "What about a small builder breakfast next month? Members could share what they're working on.",
      createdAt: "2026-10-03T09:20:00.000Z",
    },
    {
      id: "founder-venue-message",
      conversation: { kind: "channel", id: "founder-night-channel" },
      authorId: "elias",
      text: "Platform6 is confirmed. We can set up at 17:00 and open the doors at 18:00.",
      createdAt: "2026-10-03T10:05:00.000Z",
    },
    {
      id: "founder-visuals-message",
      conversation: { kind: "channel", id: "founder-night-channel" },
      authorId: "noora",
      text: "I'll have the first visuals ready on Thursday. Send me the speaker names when they're confirmed.",
      createdAt: "2026-10-03T10:12:00.000Z",
    },
    {
      id: "campus-format-message",
      conversation: { kind: "channel", id: "campus-builders-channel" },
      authorId: "diar",
      text: "Let's give teams two hours to build something small. A working demo is a better finish than a slide deck.",
      createdAt: "2026-10-03T10:30:00.000Z",
    },
    {
      id: "campus-room-message",
      conversation: { kind: "channel", id: "campus-builders-channel" },
      authorId: "leo",
      text: "I'll check the campus rooms this week. Do we expect around 30 people?",
      createdAt: "2026-10-03T10:35:00.000Z",
    },
    {
      id: "speaker-task-question",
      conversation: { kind: "task", id: "confirm-speakers" },
      authorId: "aino",
      text: "Should we invite a first-time founder too? It would make the stories more relatable for students.",
      createdAt: "2026-10-03T11:00:00.000Z",
    },
    {
      id: "speaker-task-answer",
      conversation: { kind: "task", id: "confirm-speakers" },
      authorId: "elias",
      text: "Yes. I'll ask someone building their first company and someone who's been through a few rounds.",
      createdAt: "2026-10-03T11:10:00.000Z",
    },
    {
      id: "campus-task-message",
      conversation: { kind: "task", id: "campus-format" },
      authorId: "leo",
      text: "Happy to help teams with their first prototype. We can keep the introductions to 20 minutes.",
      createdAt: "2026-10-03T11:25:00.000Z",
    },
  ],
} satisfies Workspace;
