import type { Workspace } from "@/lib/workspace";

export const demoWorkspace = {
  currentMemberId: "diar",
  members: [
    {
      id: "netta",
      name: "Netta Pihlanen",
      role: "Chair of the board",
      skills: ["Leadership", "Partnerships"],
      avatar: "/avatars/netta.jpg",
    },
    {
      id: "diar",
      name: "Diar Ghaderi",
      role: "Board member",
      skills: ["Product", "Technology"],
      avatar: "/avatars/diar.jpg",
    },
    {
      id: "jooel",
      name: "Jooel Sauramäki",
      role: "Board member",
      skills: ["Finance", "Operations"],
      avatar: "/avatars/jooel.jpg",
    },
    {
      id: "miska",
      name: "Miska Lunnas",
      role: "Board member",
      skills: ["Events", "Community"],
      avatar: "/avatars/miska.jpg",
    },
    {
      id: "siyar",
      name: "Siyarcan Yücel",
      role: "Project lead",
      skills: ["Engineering", "AI"],
      avatar: "/avatars/siyar.jpg",
    },
    {
      id: "aino",
      name: "Aino Laine",
      role: "Community lead",
      skills: ["Community", "Outreach"],
      avatar: "/avatars/aino.jpg",
    },
    {
      id: "elias",
      name: "Elias Koski",
      role: "Partnerships lead",
      skills: ["Operations", "Partnerships"],
      avatar: "/avatars/elias.jpg",
    },
    {
      id: "noora",
      name: "Noora Niemi",
      role: "Communications",
      skills: ["Design", "Marketing"],
      avatar: "/avatars/noora.jpg",
    },
    {
      id: "leo",
      name: "Leo Virtanen",
      role: "Volunteer",
      skills: ["Photography", "Technology"],
      avatar: "/avatars/leo.jpg",
    },
    {
      id: "venla",
      name: "Venla Mäkinen",
      role: "Volunteer",
      skills: ["Hosting", "Logistics"],
      avatar: "/avatars/venla.jpg",
    },
  ],
  projects: [
    {
      id: "startup-world",
      title: "Startup World Tampere",
      description:
        "TRES's flagship evening: founder keynotes, a student pitch competition, and investors meeting the Tampere startup scene.",
      status: "doing",
      assigneeIds: ["miska", "elias", "aino", "noora"],
      dueDate: "2026-11-12",
      location: "Tampere Hall, Tampere",
      capacity: 400,
      format: "in-person",
    },
    {
      id: "campus-builders",
      title: "Hacknight Series",
      description:
        "Monthly evening hacknights on campus where students form teams, build fast, and meet the TRES community.",
      status: "doing",
      assigneeIds: ["siyar", "diar", "leo"],
      dueDate: "2026-12-04",
      location: "Tampere University, Hervanta Campus",
      capacity: 60,
      format: "in-person",
    },
    {
      id: "slush-trip",
      title: "Slush 2026 Ecosystem Trip",
      description:
        "Take a group of TRES members to Slush in Helsinki to volunteer, meet founders, and bring contacts back to Tampere.",
      status: "todo",
      assigneeIds: ["netta", "jooel", "venla"],
      dueDate: "2026-11-18",
      location: "Messukeskus, Helsinki",
      capacity: 30,
      format: "in-person",
    },
  ],
  tasks: [
    {
      id: "sw-keynotes",
      title: "Confirm the keynote founders",
      description: "Two Tampere founders who have raised or exited, plus one investor fireside.",
      status: "doing",
      projectId: "startup-world",
      assigneeIds: ["elias"],
      dueDate: "2026-10-09",
      priority: "high",
      tags: ["Speakers"],
      subtasks: [
        { id: "keynote-shortlist", title: "Shortlist six founders", done: true },
        { id: "keynote-invites", title: "Send the invitations", done: true },
        { id: "keynote-topics", title: "Agree the talk topics", done: false },
        { id: "keynote-bios", title: "Collect bios and photos", done: false },
      ],
    },
    {
      id: "sw-venue",
      title: "Sign the Tampere Hall agreement",
      description: "Main hall, two side rooms for investor meetings, and the foyer for the expo.",
      status: "done",
      projectId: "startup-world",
      assigneeIds: ["elias"],
      dueDate: "2026-10-02",
      priority: "normal",
      tags: ["Venue"],
      subtasks: [],
    },
    {
      id: "sw-jury",
      title: "Assemble the pitch competition jury",
      description: "Five jurors: two investors, two founders, one Business Tampere representative.",
      status: "todo",
      projectId: "startup-world",
      assigneeIds: ["miska"],
      dueDate: "2026-10-20",
      priority: "high",
      tags: ["Speakers"],
      subtasks: [
        { id: "jury-criteria", title: "Write the judging criteria", done: false },
        { id: "jury-invite", title: "Invite the jurors", done: false },
      ],
    },
    {
      id: "sw-visuals",
      title: "Design the Startup World visuals",
      description: "Poster, social cards, stage screens, and the pitch template for teams.",
      status: "doing",
      projectId: "startup-world",
      assigneeIds: ["noora"],
      dueDate: "2026-10-14",
      priority: "normal",
      tags: ["Design"],
      subtasks: [
        { id: "visuals-poster", title: "Poster and cover image", done: true },
        { id: "visuals-social", title: "Social posts", done: false },
        { id: "visuals-pitch", title: "Pitch deck template", done: false },
      ],
    },
    {
      id: "sw-crew",
      title: "Recruit the event-day crew",
      description: "Twenty volunteers for registration, stage, expo hosts, and teardown.",
      status: "todo",
      projectId: "startup-world",
      assigneeIds: ["aino"],
      dueDate: "2026-10-24",
      priority: "high",
      tags: ["Volunteers", "Outreach"],
      subtasks: [],
    },
    {
      id: "sw-partners",
      title: "Close the partner packages",
      description: "Follow up with Business Tampere, the universities, and two startup sponsors.",
      status: "todo",
      projectId: "startup-world",
      assigneeIds: ["netta", "elias"],
      dueDate: "2026-10-16",
      priority: "urgent",
      tags: ["Outreach"],
      subtasks: [
        { id: "partners-deck", title: "Update the partner deck", done: true },
        { id: "partners-calls", title: "Book the follow-up calls", done: false },
        { id: "partners-sign", title: "Get signatures", done: false },
      ],
    },
    {
      id: "campus-format",
      title: "Choose the Hacknight format",
      description:
        "Theme per night, team size, and whether we keep the short demo round at the end.",
      status: "doing",
      projectId: "campus-builders",
      assigneeIds: ["siyar"],
      dueDate: "2026-10-10",
      priority: "high",
      tags: ["Campus"],
      subtasks: [
        { id: "format-themes", title: "Pick themes for three nights", done: true },
        { id: "format-teams", title: "Decide team size", done: false },
        { id: "format-demos", title: "Plan the demo round", done: false },
      ],
    },
    {
      id: "campus-room",
      title: "Book the Hervanta rooms for the series",
      description: "Same room every month so people know where to come.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["leo"],
      dueDate: "2026-10-12",
      priority: "normal",
      tags: ["Venue", "Campus"],
      subtasks: [
        { id: "room-shortlist", title: "Shortlist three rooms", done: true },
        { id: "room-book", title: "Confirm the bookings", done: false },
      ],
    },
    {
      id: "campus-invite",
      title: "Promote Hacknight to the student guilds",
      description:
        "Guild newsletters, Telegram groups, and a short talk at the start of a lecture.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["noora", "diar"],
      dueDate: "2026-10-15",
      priority: "normal",
      tags: ["Outreach", "Campus"],
      subtasks: [
        { id: "invite-copy", title: "Write the copy", done: false },
        { id: "invite-guilds", title: "Send to guild boards", done: false },
      ],
    },
    {
      id: "campus-mentors",
      title: "Invite Hack for Humanity mentors back",
      description: "Ask the mentors from Hack for Humanity to drop in at the October hacknight.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["aino", "siyar"],
      dueDate: "2026-10-17",
      priority: "low",
      tags: ["Speakers"],
      subtasks: [],
    },
    {
      id: "slush-tickets",
      title: "Secure Slush volunteer spots",
      description: "Apply for a TRES volunteer block so members get in and work the floor.",
      status: "todo",
      projectId: "slush-trip",
      assigneeIds: ["netta"],
      dueDate: "2026-10-13",
      priority: "urgent",
      tags: ["Volunteers"],
      subtasks: [],
    },
    {
      id: "slush-travel",
      title: "Book the bus from Tampere to Helsinki",
      description: "Return trip for thirty people, leaving early on day one.",
      status: "todo",
      projectId: "slush-trip",
      assigneeIds: ["jooel", "venla"],
      dueDate: "2026-10-30",
      priority: "normal",
      tags: [],
      subtasks: [
        { id: "travel-quotes", title: "Get three quotes", done: false },
        { id: "travel-budget", title: "Check against the budget", done: false },
      ],
    },
    {
      id: "slush-meetings",
      title: "Line up startup meetings at Slush",
      description: "Tampere startups that want students to visit their booth or side event.",
      status: "todo",
      projectId: "slush-trip",
      assigneeIds: ["diar", "miska"],
      dueDate: "2026-11-06",
      priority: "normal",
      tags: ["Outreach"],
      subtasks: [],
    },
    {
      id: "board-agenda",
      title: "Prepare the next board agenda",
      description: "Budget review, Startup World status, and the Summer Founders Program decision.",
      status: "doing",
      projectId: null,
      assigneeIds: ["netta", "diar"],
      dueDate: "2026-10-06",
      priority: "urgent",
      tags: ["Board"],
      subtasks: [
        { id: "agenda-collect", title: "Collect open questions", done: true },
        { id: "agenda-share", title: "Share before Tuesday", done: false },
      ],
    },
    {
      id: "h4h-followup",
      title: "Send the Hack for Humanity follow-ups",
      description: "Thank the participants, share photos, and invite teams to the next hacknight.",
      status: "todo",
      projectId: null,
      assigneeIds: ["miska", "leo"],
      dueDate: "2026-10-07",
      priority: "high",
      tags: ["Outreach"],
      subtasks: [],
    },
    {
      id: "summer-founders",
      title: "Draft the Summer Founders Program call",
      description: "Application form and timeline for next summer's student founder cohort.",
      status: "todo",
      projectId: null,
      assigneeIds: ["siyar", "netta"],
      dueDate: "2026-11-30",
      priority: "low",
      tags: ["Board"],
      subtasks: [],
    },
    {
      id: "drive-folder",
      title: "Organize the shared project documents",
      description: "One folder per project, with the budget sheet and contracts linked from each.",
      status: "done",
      projectId: null,
      assigneeIds: ["jooel", "venla"],
      dueDate: "2026-10-01",
      priority: "low",
      tags: ["Board"],
      subtasks: [
        { id: "drive-structure", title: "Set up the folder structure", done: true },
        { id: "drive-move", title: "Move the old files", done: true },
      ],
    },
    {
      id: "grant-application",
      title: "Submit the city youth grant application",
      description: "Finish the budget section and attach last year's activity report.",
      status: "doing",
      projectId: null,
      assigneeIds: ["elias"],
      dueDate: "2026-10-10",
      priority: "high",
      tags: ["Board"],
      subtasks: [
        { id: "grant-budget", title: "Write the budget section", done: true },
        { id: "grant-report", title: "Attach the activity report", done: false },
        { id: "grant-submit", title: "Submit on the city portal", done: false },
      ],
    },
    {
      id: "newsletter",
      title: "Send the October newsletter",
      description: "Highlights from Hack for Humanity and what is coming up this month.",
      status: "doing",
      projectId: null,
      assigneeIds: ["noora"],
      dueDate: "2026-10-07",
      priority: "normal",
      tags: ["Outreach", "Design"],
      subtasks: [
        { id: "newsletter-draft", title: "Draft the stories", done: true },
        { id: "newsletter-photos", title: "Pick event photos", done: false },
      ],
    },
    {
      id: "university-reply",
      title: "Reply to the university partnership email",
      description: "Tampere University wants to co-host a spring event. Answer with dates.",
      status: "todo",
      projectId: null,
      assigneeIds: ["diar"],
      dueDate: "2026-10-05",
      priority: "urgent",
      tags: ["Board", "Campus"],
      subtasks: [],
    },
    {
      id: "merch-order",
      title: "Order TRES stickers and hoodies",
      description: "Get quotes from two local printers and order before Startup World.",
      status: "todo",
      projectId: null,
      assigneeIds: ["leo"],
      dueDate: "2026-10-17",
      priority: "low",
      tags: ["Design"],
      subtasks: [
        { id: "merch-quotes", title: "Get two quotes", done: false },
        { id: "merch-sizes", title: "Collect hoodie sizes", done: false },
      ],
    },
  ],
  channels: [
    { id: "general", name: "general", kind: "general" },
    { id: "board", name: "board", kind: "general" },
    { id: "ideas", name: "ideas", kind: "general" },
    {
      id: "startup-world-channel",
      name: "Startup World Tampere",
      kind: "project",
      projectId: "startup-world",
    },
    {
      id: "campus-builders-channel",
      name: "Hacknight Series",
      kind: "project",
      projectId: "campus-builders",
    },
    {
      id: "slush-trip-channel",
      name: "Slush 2026 Ecosystem Trip",
      kind: "project",
      projectId: "slush-trip",
    },
  ],
  messages: [
    {
      id: "general-kickoff",
      conversation: { kind: "channel", id: "general" },
      authorId: "netta",
      source: "workspace",
      text: "Autumn is on. Startup World Tampere, the Hacknight Series, and the Slush trip are our three big projects until December.",
      createdAt: "2026-10-01T06:40:00.000Z",
    },
    {
      id: "general-roles",
      conversation: { kind: "channel", id: "general" },
      authorId: "netta",
      source: "workspace",
      text: "Grab a task on the board if you want to own a piece of any of them.",
      createdAt: "2026-10-01T06:42:00.000Z",
    },
    {
      id: "general-hello",
      conversation: { kind: "channel", id: "general" },
      authorId: "aino",
      source: "workspace",
      text: "Hack for Humanity is today at Campus Areena. Doors at 9:00, come say hi even if you're not hacking.",
      createdAt: "2026-10-03T05:15:00.000Z",
    },
    {
      id: "general-help",
      conversation: { kind: "channel", id: "general" },
      authorId: "leo",
      source: "workspace",
      text: "I'm on photos today. I'll share the album in the drive tonight.",
      createdAt: "2026-10-03T06:28:00.000Z",
    },
    {
      id: "board-budget",
      conversation: { kind: "channel", id: "board" },
      authorId: "jooel",
      source: "workspace",
      text: "Autumn budget is in the drive. Startup World is the biggest line, then the Slush bus.",
      createdAt: "2026-10-01T15:00:00.000Z",
    },
    {
      id: "board-agenda-note",
      conversation: { kind: "channel", id: "board" },
      authorId: "netta",
      source: "workspace",
      text: "Agenda for Tuesday: budget, partner packages, and whether we run Summer Founders again.",
      createdAt: "2026-10-02T09:10:00.000Z",
    },
    {
      id: "ideas-healthtech",
      conversation: { kind: "channel", id: "ideas" },
      authorId: "siyar",
      source: "workspace",
      text: "What if one hacknight is health tech? I can bring a few medical students and a real dataset.",
      createdAt: "2026-10-02T19:20:00.000Z",
    },
    {
      id: "sw-channel-keynotes",
      conversation: { kind: "channel", id: "startup-world-channel" },
      authorId: "elias",
      source: "workspace",
      text: "Two keynotes said yes. Waiting on the investor for the fireside.",
      createdAt: "2026-10-02T13:30:00.000Z",
    },
    {
      id: "sw-channel-visuals",
      conversation: { kind: "channel", id: "startup-world-channel" },
      authorId: "noora",
      source: "workspace",
      text: "Poster draft is up. Feedback before Friday please.",
      createdAt: "2026-10-03T07:05:00.000Z",
    },
    {
      id: "hacknight-channel",
      conversation: { kind: "channel", id: "campus-builders-channel" },
      authorId: "siyar",
      source: "workspace",
      text: "First hacknight is 23 October in Hervanta. Luma page is live as a draft.",
      createdAt: "2026-10-02T16:45:00.000Z",
    },
    {
      id: "slush-channel",
      conversation: { kind: "channel", id: "slush-trip-channel" },
      authorId: "jooel",
      source: "workspace",
      text: "Collecting bus quotes this week. Put your name in the sheet if you want a seat.",
      createdAt: "2026-10-02T11:00:00.000Z",
    },
    {
      id: "campus-task-message",
      conversation: { kind: "task", id: "campus-format" },
      authorId: "leo",
      source: "workspace",
      text: "Happy to help teams with their first prototype. Keep the intro to 20 minutes so people get building.",
      createdAt: "2026-10-03T08:25:00.000Z",
    },
    {
      id: "dm-aino-earlier",
      conversation: { kind: "direct", id: "aino" },
      authorId: "aino",
      source: "workspace",
      text: "Thanks for picking up the board agenda.",
      createdAt: "2026-10-02T14:02:00.000Z",
    },
    {
      id: "dm-aino",
      conversation: { kind: "direct", id: "aino" },
      authorId: "aino",
      source: "workspace",
      text: "Can you look at the Startup World crew list before Tuesday?",
      createdAt: "2026-10-03T08:40:00.000Z",
    },
    {
      id: "dm-leo",
      conversation: { kind: "direct", id: "leo" },
      authorId: "leo",
      source: "workspace",
      text: "Hack for Humanity photos will be in the drive tonight.",
      createdAt: "2026-10-03T08:48:00.000Z",
    },
    {
      id: "dm-siyar",
      conversation: { kind: "direct", id: "siyar" },
      authorId: "siyar",
      source: "workspace",
      text: "Hacknight format draft is in the task. Can you review it tonight?",
      createdAt: "2026-10-03T09:10:00.000Z",
    },
    {
      id: "dm-netta",
      conversation: { kind: "direct", id: "netta" },
      authorId: "netta",
      source: "workspace",
      text: "Let's lock the board agenda on Monday. Add the budget item from Jooel.",
      createdAt: "2026-10-03T06:15:00.000Z",
    },
    {
      id: "dm-miska",
      conversation: { kind: "direct", id: "miska" },
      authorId: "miska",
      source: "workspace",
      text: "Hack for Humanity hosts are confirmed. I'll share the check-in plan.",
      createdAt: "2026-10-02T17:30:00.000Z",
    },
    {
      id: "dm-jooel",
      conversation: { kind: "direct", id: "jooel" },
      authorId: "jooel",
      source: "workspace",
      text: "Sent the autumn budget numbers to the drive folder.",
      createdAt: "2026-10-01T15:05:00.000Z",
    },
  ],
} satisfies Workspace;
