import type { Workspace } from "@/lib/workspace";

export const demoWorkspace = {
  currentMemberId: "diar",
  members: [
    {
      id: "netta",
      name: "Netta Pihlanen",
      role: "Chair of the board",
      skills: ["Leadership", "Partnerships"],
      avatar: "/avatars/netta.jpg",
    },
    {
      id: "diar",
      name: "Diar Ghaderi",
      role: "Board member",
      skills: ["Product", "Technology"],
      avatar: "/avatars/diar.jpg",
    },
    {
      id: "jooel",
      name: "Jooel Sauramäki",
      role: "Board member",
      skills: ["Finance", "Operations"],
      avatar: "/avatars/jooel.jpg",
    },
    {
      id: "miska",
      name: "Miska Lunnas",
      role: "Board member",
      skills: ["Events", "Community"],
      avatar: "/avatars/miska.jpg",
    },
    {
      id: "siyar",
      name: "Siyarcan Yücel",
      role: "Project lead",
      skills: ["Engineering", "AI"],
      avatar: "/avatars/siyar.jpg",
    },
    {
      id: "aino",
      name: "Aino Laine",
      role: "Community lead",
      skills: ["Community", "Outreach"],
      avatar: "/avatars/aino.jpg",
    },
    {
      id: "elias",
      name: "Elias Koski",
      role: "Partnerships lead",
      skills: ["Operations", "Partnerships"],
      avatar: "/avatars/elias.jpg",
    },
    {
      id: "noora",
      name: "Noora Niemi",
      role: "Communications",
      skills: ["Design", "Marketing"],
      avatar: "/avatars/noora.jpg",
    },
    {
      id: "leo",
      name: "Leo Virtanen",
      role: "Volunteer",
      skills: ["Photography", "Technology"],
      avatar: "/avatars/leo.jpg",
    },
    {
      id: "venla",
      name: "Venla Mäkinen",
      role: "Volunteer",
      skills: ["Hosting", "Logistics"],
      avatar: "/avatars/venla.jpg",
    },
  ],
  projects: [
    {
      id: "founder-night",
      title: "Founder Night",
      description:
        "An evening of honest founder stories, new connections, and ideas worth building.",
      status: "doing",
      assigneeIds: ["miska", "elias", "aino", "noora"],
      dueDate: "2026-10-22",
      location: "Platform6, Tampere",
      capacity: 80,
      format: "in-person",
    },
    {
      id: "campus-builders",
      title: "Campus Builders",
      description:
        "Bring students together to form teams and turn early ideas into working projects.",
      status: "todo",
      assigneeIds: ["siyar", "diar", "leo"],
      dueDate: "2026-11-05",
      location: "Tampere University, City Centre Campus",
      capacity: 40,
      format: "in-person",
    },
  ],
  tasks: [
    {
      id: "confirm-speakers",
      title: "Confirm the founder speakers",
      description: "Invite two local founders and confirm the topics they want to share.",
      status: "doing",
      projectId: "founder-night",
      assigneeIds: ["elias"],
      dueDate: "2026-10-08",
      priority: "high",
      tags: ["Speakers"],
      subtasks: [
        { id: "speaker-shortlist", title: "Shortlist six founders", done: true },
        { id: "speaker-outreach", title: "Send the invitations", done: true },
        { id: "speaker-topics", title: "Agree the talk topics", done: false },
        { id: "speaker-bios", title: "Collect bios and photos", done: false },
      ],
    },
    {
      id: "book-venue",
      title: "Book the space at Platform6",
      description: "Confirm the room, capacity, and access for the organizing team.",
      status: "done",
      projectId: "founder-night",
      assigneeIds: ["elias"],
      dueDate: "2026-10-02",
      priority: "normal",
      tags: ["Venue"],
      subtasks: [],
    },
    {
      id: "founder-visuals",
      title: "Design the Founder Night visuals",
      description: "Prepare the project cover and social posts for the launch.",
      status: "doing",
      projectId: "founder-night",
      assigneeIds: ["noora"],
      dueDate: "2026-10-09",
      priority: "normal",
      tags: ["Design"],
      subtasks: [
        { id: "visuals-cover", title: "Project cover image", done: true },
        { id: "visuals-social", title: "Social posts", done: false },
      ],
    },
    {
      id: "welcome-team",
      title: "Find a welcome team",
      description: "Ask members in Telegram who would like to greet guests and help with check-in.",
      status: "todo",
      projectId: "founder-night",
      assigneeIds: ["aino"],
      dueDate: "2026-10-12",
      priority: "high",
      tags: ["Volunteers", "Outreach"],
      subtasks: [
        { id: "visuals-cover", title: "Project cover image", done: true },
        { id: "visuals-social", title: "Social posts", done: false },
      ],
    },
    {
      id: "photography",
      title: "Plan photos for Founder Night",
      description: "Agree on the moments to capture and where to share the album afterward.",
      status: "todo",
      projectId: "founder-night",
      assigneeIds: ["leo"],
      dueDate: "2026-10-16",
      priority: "low",
      tags: ["Design"],
      subtasks: [],
    },
    {
      id: "founder-run-sheet",
      title: "Write the evening run sheet",
      description: "Draft the timings for setup, talks, questions, and networking.",
      status: "todo",
      projectId: "founder-night",
      assigneeIds: ["elias", "aino"],
      dueDate: "2026-10-15",
      priority: "high",
      tags: ["Volunteers"],
      subtasks: [
        { id: "runsheet-setup", title: "Setup and doors", done: false },
        { id: "runsheet-talks", title: "Talks and Q&A timings", done: false },
        { id: "runsheet-close", title: "Networking and close", done: false },
      ],
    },
    {
      id: "campus-format",
      title: "Choose the Campus Builders format",
      description:
        "Keep the first session practical, with introductions, team formation, and time to build.",
      status: "doing",
      projectId: "campus-builders",
      assigneeIds: ["siyar"],
      dueDate: "2026-10-13",
      priority: "normal",
      tags: ["Campus"],
      subtasks: [
        { id: "runsheet-setup", title: "Setup and doors", done: false },
        { id: "runsheet-talks", title: "Talks and Q&A timings", done: false },
        { id: "runsheet-close", title: "Networking and close", done: false },
      ],
    },
    {
      id: "campus-room",
      title: "Reserve a campus room",
      description: "Find a room with tables, power, and space for small teams.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["leo"],
      dueDate: "2026-10-16",
      priority: "high",
      tags: ["Campus", "Venue"],
      subtasks: [
        { id: "room-shortlist", title: "Shortlist three rooms", done: true },
        { id: "room-book", title: "Confirm the booking", done: false },
      ],
    },
    {
      id: "campus-invite",
      title: "Draft the student invitation",
      description: "Explain what participants can build and that no finished idea is required.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["noora", "diar"],
      dueDate: "2026-10-20",
      priority: "normal",
      tags: ["Campus", "Outreach"],
      subtasks: [
        { id: "invite-draft", title: "Draft the copy", done: false },
        { id: "invite-review", title: "Review with the board", done: false },
        { id: "invite-send", title: "Send to student lists", done: false },
      ],
    },
    {
      id: "campus-mentors",
      title: "Invite mentors for builder teams",
      description: "Ask a few experienced members to help teams get past their first blockers.",
      status: "todo",
      projectId: "campus-builders",
      assigneeIds: ["aino"],
      dueDate: "2026-10-23",
      priority: "low",
      tags: ["Campus", "Volunteers"],
      subtasks: [
        { id: "room-shortlist", title: "Shortlist three rooms", done: true },
        { id: "room-book", title: "Confirm the booking", done: false },
      ],
    },
    {
      id: "board-agenda",
      title: "Prepare the next board agenda",
      description: "Collect decisions and open questions from this week's project discussions.",
      status: "doing",
      projectId: null,
      assigneeIds: ["netta", "diar"],
      dueDate: "2026-10-06",
      priority: "urgent",
      tags: ["Board"],
      subtasks: [
        { id: "agenda-collect", title: "Collect open questions", done: true },
        { id: "agenda-share", title: "Share before Tuesday", done: false },
      ],
    },
    {
      id: "member-onboarding",
      title: "Refresh member onboarding",
      description: "Make it easy for new members to find a project and meet the team.",
      status: "todo",
      projectId: null,
      assigneeIds: ["aino", "noora"],
      dueDate: "2026-10-14",
      priority: "normal",
      tags: ["Outreach"],
      subtasks: [
        { id: "invite-draft", title: "Draft the copy", done: false },
        { id: "invite-review", title: "Review with the board", done: false },
        { id: "invite-send", title: "Send to student lists", done: false },
      ],
    },
    {
      id: "drive-folder",
      title: "Organize the shared project documents",
      description: "Put the current briefs and checklists in one shared Drive folder.",
      status: "done",
      projectId: null,
      assigneeIds: ["jooel", "venla"],
      dueDate: "2026-10-01",
      priority: "low",
      tags: ["Board"],
      subtasks: [
        { id: "agenda-collect", title: "Collect open questions", done: true },
        { id: "agenda-share", title: "Share before Tuesday", done: false },
      ],
    },
  ],
  channels: [
    { id: "general", name: "general", kind: "general" },
    { id: "board", name: "board", kind: "general" },
    { id: "ideas", name: "ideas", kind: "general" },
    {
      id: "founder-night-channel",
      name: "Founder Night",
      kind: "project",
      projectId: "founder-night",
    },
    {
      id: "campus-builders-channel",
      name: "Campus Builders",
      kind: "project",
      projectId: "campus-builders",
    },
  ],
  messages: [
    {
      id: "general-kickoff",
      conversation: { kind: "channel", id: "general" },
      authorId: "diar",
      text: "Autumn season is live. Founder Night and Campus Builders are the two projects we're running until November.",
      createdAt: "2026-10-01T06:40:00.000Z",
    },
    {
      id: "general-roles",
      conversation: { kind: "channel", id: "general" },
      authorId: "diar",
      text: "Shout if you want to own a piece of either one.",
      createdAt: "2026-10-01T06:42:00.000Z",
    },
    {
      id: "general-hello",
      conversation: { kind: "channel", id: "general" },
      authorId: "aino",
      text: "Welcome back! Founder Night and Campus Builders are taking shape. Pick a task if you'd like to help.",
      createdAt: "2026-10-02T08:15:00.000Z",
    },
    {
      id: "general-help",
      conversation: { kind: "channel", id: "general" },
      authorId: "leo",
      text: "I'm in for photos at Founder Night. I'll also check rooms for the campus session.",
      createdAt: "2026-10-03T08:28:00.000Z",
    },
    {
      id: "board-budget",
      conversation: { kind: "channel", id: "board" },
      authorId: "elias",
      text: "Venue deposit is paid. I'll add the receipt to the shared folder.",
      createdAt: "2026-10-02T12:05:00.000Z",
    },
    {
      id: "board-agenda-message",
      conversation: { kind: "channel", id: "board" },
      authorId: "diar",
      text: "Let's bring the project budgets and volunteer needs to Tuesday's board meeting.",
      createdAt: "2026-10-03T09:00:00.000Z",
    },
    {
      id: "idea-breakfast",
      conversation: { kind: "channel", id: "ideas" },
      authorId: "noora",
      text: "What about a small builder breakfast next month? Members could share what they're working on.",
      createdAt: "2026-10-02T09:20:00.000Z",
    },
    {
      id: "idea-breakfast-reply",
      conversation: { kind: "channel", id: "ideas" },
      authorId: "aino",
      text: "I like it. Low effort, and it keeps people talking between the bigger events.",
      createdAt: "2026-10-03T07:05:00.000Z",
    },
    {
      id: "founder-venue-message",
      conversation: { kind: "channel", id: "founder-night-channel" },
      authorId: "elias",
      text: "Platform6 is confirmed. We can set up at 17:00 and open the doors at 18:00.",
      createdAt: "2026-10-01T10:05:00.000Z",
    },
    {
      id: "founder-capacity",
      conversation: { kind: "channel", id: "founder-night-channel" },
      authorId: "elias",
      text: "Room fits 80 comfortably, so let's cap registration there.",
      createdAt: "2026-10-01T10:08:00.000Z",
    },
    {
      id: "founder-visuals-message",
      conversation: { kind: "channel", id: "founder-night-channel" },
      authorId: "noora",
      text: "I'll have the first visuals ready on Thursday. Send me the speaker names when they're confirmed.",
      createdAt: "2026-10-02T10:12:00.000Z",
    },
    {
      id: "founder-runsheet-nudge",
      conversation: { kind: "channel", id: "founder-night-channel" },
      authorId: "aino",
      text: "Run sheet is still open. I'll draft it tonight unless someone already started.",
      createdAt: "2026-10-03T09:45:00.000Z",
    },
    {
      id: "campus-format-message",
      conversation: { kind: "channel", id: "campus-builders-channel" },
      authorId: "diar",
      text: "Let's give teams two hours to build something small. A working demo is a better finish than a slide deck.",
      createdAt: "2026-10-02T10:30:00.000Z",
    },
    {
      id: "campus-room-message",
      conversation: { kind: "channel", id: "campus-builders-channel" },
      authorId: "leo",
      text: "I'll check the campus rooms this week. Do we expect around 30 people?",
      createdAt: "2026-10-03T10:35:00.000Z",
    },
    {
      id: "speaker-task-question",
      conversation: { kind: "task", id: "confirm-speakers" },
      authorId: "aino",
      text: "Should we invite a first-time founder too? It would make the stories more relatable for students.",
      createdAt: "2026-10-02T11:00:00.000Z",
    },
    {
      id: "speaker-task-answer",
      conversation: { kind: "task", id: "confirm-speakers" },
      authorId: "elias",
      text: "Yes. I'll ask someone building their first company and someone who's been through a few rounds.",
      createdAt: "2026-10-03T11:10:00.000Z",
    },
    {
      id: "campus-task-message",
      conversation: { kind: "task", id: "campus-format" },
      authorId: "leo",
      text: "Happy to help teams with their first prototype. We can keep the introductions to 20 minutes.",
      createdAt: "2026-10-03T11:25:00.000Z",
    },
    {
      id: "dm-aino-earlier",
      conversation: { kind: "direct", id: "aino" },
      authorId: "aino",
      text: "Thanks for picking up the board agenda.",
      createdAt: "2026-10-02T14:02:00.000Z",
    },
    {
      id: "dm-aino",
      conversation: { kind: "direct", id: "aino" },
      authorId: "aino",
      text: "Can you look at the welcome team list before Tuesday?",
      createdAt: "2026-10-03T11:40:00.000Z",
    },
    {
      id: "dm-leo",
      conversation: { kind: "direct", id: "leo" },
      authorId: "leo",
      text: "I'll send the photo plan once the run sheet is ready.",
      createdAt: "2026-10-03T11:48:00.000Z",
    },
    {
      id: "dm-siyar",
      conversation: { kind: "direct", id: "siyar" },
      authorId: "siyar",
      text: "Campus Builders format draft is in the task. Can you review it tonight?",
      createdAt: "2026-10-03T12:10:00.000Z",
    },
    {
      id: "dm-netta",
      conversation: { kind: "direct", id: "netta" },
      authorId: "netta",
      text: "Let's lock the board agenda on Monday. Add the budget item from Jooel.",
      createdAt: "2026-10-03T09:15:00.000Z",
    },
    {
      id: "dm-miska",
      conversation: { kind: "direct", id: "miska" },
      authorId: "miska",
      text: "Hack for Humanity hosts are confirmed. I'll share the check-in plan.",
      createdAt: "2026-10-02T17:30:00.000Z",
    },
    {
      id: "dm-jooel",
      conversation: { kind: "direct", id: "jooel" },
      authorId: "jooel",
      text: "Sent the autumn budget numbers to the drive folder.",
      createdAt: "2026-10-01T15:05:00.000Z",
    },
  ],
} satisfies Workspace;
